// Generated by Tools/build-scripts.js. Edit src/ or Rules/personal/ and rebuild.

const ruleProviderDefinitions = {
  "ads": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-ads.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/ads.mrs"
  },
  "ai": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-ai.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/ai.mrs"
  },
  "apple": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-apple.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/apple.mrs"
  },
  "direct-lite": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-direct-lite.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/direct-lite.mrs"
  },
  "direct_ip": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "ipcidr",
    "format": "mrs",
    "path": "./rules/personal-direct_ip.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/ipcidr/direct_ip.mrs"
  },
  "dlsite": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-dlsite.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/dlsite.mrs"
  },
  "dnsmasq-china-lite": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-dnsmasq-china-lite.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/dnsmasq-china-lite.mrs"
  },
  "download": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-download.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/download.mrs"
  },
  "ehentai": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-ehentai.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/ehentai.mrs"
  },
  "facebook_ip": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "ipcidr",
    "format": "mrs",
    "path": "./rules/personal-facebook_ip.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/ipcidr/facebook_ip.mrs"
  },
  "google": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-google.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/google.mrs"
  },
  "google_ip": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "ipcidr",
    "format": "mrs",
    "path": "./rules/personal-google_ip.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/ipcidr/google_ip.mrs"
  },
  "googlefcm": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-googlefcm.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/googlefcm.mrs"
  },
  "line": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-line.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/line.mrs"
  },
  "media": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-media.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/media.mrs"
  },
  "media_ip": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "ipcidr",
    "format": "mrs",
    "path": "./rules/personal-media_ip.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/ipcidr/media_ip.mrs"
  },
  "meta": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-meta.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/meta.mrs"
  },
  "microsoft": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-microsoft.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/microsoft.mrs"
  },
  "netflix": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-netflix.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/netflix.mrs"
  },
  "pikpak": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-pikpak.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/pikpak.mrs"
  },
  "proxy-lite": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-proxy-lite.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/proxy-lite.mrs"
  },
  "proxy@direct": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-proxy@direct.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/proxy@direct.mrs"
  },
  "safe": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-safe.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/safe.mrs"
  },
  "safe_ip": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "ipcidr",
    "format": "mrs",
    "path": "./rules/personal-safe_ip.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/ipcidr/safe_ip.mrs"
  },
  "steam": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-steam.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/steam.mrs"
  },
  "telegram": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-telegram.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/telegram.mrs"
  },
  "telegram_ip": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "ipcidr",
    "format": "mrs",
    "path": "./rules/personal-telegram_ip.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/ipcidr/telegram_ip.mrs"
  },
  "twitter": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-twitter.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/twitter.mrs"
  },
  "youtube": {
    "type": "http",
    "interval": 86400,
    "proxy": "代理连接",
    "behavior": "domain",
    "format": "mrs",
    "path": "./rules/personal-youtube.mrs",
    "url": "https://raw.githubusercontent.com/ValoHalo/ConfigProcessScript/main/Rules/generated/domain/youtube.mrs"
  }
};

const applicationGroups = [
  {
    "name": "FCM",
    "domain": "googlefcm",
    "defaultGroup": "直接连接",
    "enabled": true
  },
  {
    "name": "YouTube",
    "domain": "youtube",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "TELEGRAM",
    "domain": "telegram",
    "existingGroup": true,
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "Microsoft",
    "domain": "microsoft",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "Apple",
    "domain": "apple",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "Steam",
    "domain": "steam",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "Twitter",
    "domain": "twitter",
    "baseIp": "safe_ip",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "Meta",
    "domain": "meta",
    "ip": "facebook_ip",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "Line",
    "domain": "line",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "Netflix",
    "domain": "netflix",
    "baseIp": "media_ip",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "PikPak",
    "domain": "pikpak",
    "defaultGroup": "代理连接",
    "enabled": true
  },
  {
    "name": "EHentai",
    "domain": "ehentai",
    "defaultGroup": "美国",
    "enabled": true
  }
];

// Base configuration adapted from https://github.com/echs-top/proxy (1f35b88941854531a2876382bb29d234850da57b).
// Maintained here; published rule providers come from config/rule-sources.json.

function buildBaseConfig(config) {
  const subscriptionProxies = config.proxies || [];
  const optionalProviders = new Set(['dlsite', ...applicationGroups.flatMap(app => [app.domain, app.ip].filter(Boolean))]);
  const directDns = ["https://dns.alidns.com/dns-query#直接连接", "https://doh.pub/dns-query#直接连接&h3=false"];
  const proxyDns = ["https://dns.google/dns-query#代理DNS&ecs=8.8.8.8/24&ecs-override=true", "https://dns.quad9.net/dns-query#代理DNS&ecs=9.9.9.9/24&ecs-override=true"];
  const balAnchor = { "type": "load-balance", "strategy": "round-robin", "include-all-providers": true, "empty-fallback": "REJECT", "hidden": true };
  const fallAnchor = { "type": "fallback", "include-all-providers": true, "empty-fallback": "REJECT", "hidden": true };
  const dlAnchor = { "type": "select", "proxies": ["代理连接", "直接连接", "最低延迟", "故障转移", "香港|故障转移", "台湾|故障转移", "新加坡|故障转移", "日本|故障转移", "美国|故障转移", "德国|故障转移", "英国|故障转移", "荷兰|故障转移", "香港|轮询下载", "新加坡|轮询下载", "日本|轮询下载", "美国|轮询下载"], "include-all-providers": true, "empty-fallback": "REJECT" };
  const originDns = config.dns || {};
  const appendDirectTag = (val) => { if (typeof val === 'string') { return val.split('#')[0] + '#直接连接'; } return val; };
  const formatDnsValues = (dnsValue) => { if (Array.isArray(dnsValue)) return dnsValue.map(appendDirectTag); return appendDirectTag(dnsValue); };
  let finalProxyServerNameserver = directDns;
  const originPsn = originDns['proxy-server-nameserver'];
  if (originPsn != null && originPsn !== '' && (!Array.isArray(originPsn) || originPsn.length > 0)) { finalProxyServerNameserver = formatDnsValues(originPsn); }
  let finalProxyServerNameserverPolicy = undefined;
  const originPolicy = originDns['proxy-server-nameserver-policy'];
  if (originPolicy && typeof originPolicy === 'object' && !Array.isArray(originPolicy) && Object.keys(originPolicy).length > 0) { finalProxyServerNameserverPolicy = {}; for (const [domain, servers] of Object.entries(originPolicy)) { finalProxyServerNameserverPolicy[domain] = formatDnsValues(servers); } }
  const originHosts = config.hosts || {};
  const defaultHosts = {
    "dns.alidns.com": ["223.5.5.5", "223.6.6.6", "2400:3200::1", "2400:3200:baba::1"],
    "doh.pub": ["120.53.53.53", "1.12.12.12"],
    "dns.google": ["8.8.8.8", "8.8.4.4", "2001:4860:4860::8888", "2001:4860:4860::8844"],
    "dns.quad9.net": ["9.9.9.9", "149.112.112.112", "2620:fe::fe", "2620:fe::9"],
    "services.googleapis.cn": "services.googleapis.com",
    "google.cn": "google.com",
    "cn.bing.com": "global.bing.com"
  };
  const finalHosts = { ...originHosts, ...defaultHosts };
  const quic = "AND,((NETWORK,udp),(DST-PORT,443)),代理QUIC";
  return { 
    // 节点IP优先级：ip-version: ipv6-prefer
    "proxy-providers": { "节点": { "type": "inline", "health-check": { "enable": true, "url": "https://dns.google/generate_204", "expected-status": 204, "interval": 600, "timeout": 3000, "max-failed-times": 2, "lazy": false }, "override": { "ip-version": "dual" }, "exclude-filter": "(?i)套餐|剩余|流量|到期|重置|频道|订阅|官网|禁止|客户端|有效|联系|测试|节点|日期|群组|加入|通知|维护|网址|地址|下载|更新|APP|登录|严禁|恢复|处理|谢谢", "payload": subscriptionProxies } },
    "ipv6": true,
    "allow-lan": false,
    "bind-address": "*",
    "mode": "rule",
    "log-level": "error",
    "unified-delay": true,
    "tcp-concurrent": true,
    "find-process-mode": "off",
    "disable-keep-alive": false,
    "keep-alive-interval": 15,
    "keep-alive-idle": 600,
    "etag-support": true,
    // "global-ua": "Mozilla/5.0 (Linux; Android 16; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.7778.217 Mobile Safari/537.36",
    // "global-ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.7778.257 Safari/537.36",
    // "external-controller": "[::]:9090",
    // "secret": "密码",
    // "external-doh-server": "/dns-query",
    // "external-ui": "./zashboard",
    // 霞鹜文楷：https://github.com/echs-top/proxy/releases/download/zashboard/dist.zip
    // "external-ui-url": "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip",
    "profile": { "store-selected": true, "store-fake-ip": true },
    "experimental": { "quic-go-disable-gso": false, "quic-go-disable-ecn": true, "dialer-ip4p-convert": false },
    "port": 0,
    "socks-port": 0,
    "mixed-port": 0,
    "redir-port": 0,
    "tproxy-port": 0,
    "tun": {
      "enable": true,
      // Android dummy9 / Windows "以太网 9" / MacOS utun9
      // "device": "dummy9",
      "stack": "mixed",
      "auto-route": true,
      "auto-redirect": true,
      "auto-detect-interface": true,
      "strict-route": true,
      "disable-icmp-forwarding": true,
      // "endpoint-independent-nat": true,
      "dns-hijack": ["any:53", "tcp://any:53"],
      "udp-timeout": 600
    },
    "hosts": finalHosts,
    "dns": {
      "enable": true,
      "ipv6": true,
      "ipv6-timeout": 300,
      "cache-algorithm": "arc",
      "use-hosts": true,
      "use-system-hosts": false,
      "prefer-h3": true,
      "respect-rules": false,
      // "listen": "[::]:1053",
      "enhanced-mode": "fake-ip",
      "fake-ip-range": "198.18.0.0/15",
      "fake-ip-range6": "fd00:a4c5:9b12:d3f8:e760:00df::/96",
      "fake-ip-ttl": 1,
      "fake-ip-filter-mode": "rule",
      "fake-ip-filter": [
        "RULE-SET,ads,fake-ip",
        "RULE-SET,proxy@direct,real-ip",
        "RULE-SET,ai,fake-ip",
        "RULE-SET,download,fake-ip",
        "RULE-SET,safe,fake-ip",
        "RULE-SET,google,fake-ip",
        "RULE-SET,media,fake-ip",
        "RULE-SET,proxy-lite,fake-ip",
        "RULE-SET,direct-lite,real-ip",
        "MATCH,fake-ip"
      ],
      "default-nameserver": ["223.6.6.6", "119.29.29.29"],
      "proxy-server-nameserver": finalProxyServerNameserver,
      ...(finalProxyServerNameserverPolicy !== undefined && { "proxy-server-nameserver-policy": finalProxyServerNameserverPolicy }),
      "nameserver": proxyDns,
      "nameserver-policy": {
        "rule-set:ads": ["rcode://name_error"],
        "rule-set:proxy@direct": directDns,
        "rule-set:ai,download,safe,google,media,proxy-lite": proxyDns,
        "rule-set:direct-lite,dnsmasq-china-lite": directDns
      },
      "direct-nameserver": directDns,
      "direct-nameserver-follow-policy": true
    },
    "sniffer": {
      "enable": true,
      "force-dns-mapping": true,
      "parse-pure-ip": true,
      "override-destination": false,
      "sniff": { "HTTP": { "ports": [80, "8080-8880"], "override-destination": true }, "TLS": { "ports": [443, 8443] }, "QUIC": { "ports": [443, 8443] } },
      "skip-domain": ["rule-set:ads,proxy@direct,ai,download,safe,google,media,proxy-lite,direct-lite,dnsmasq-china-lite"],
      "skip-src-address": ["rule-set:telegram_ip,safe_ip,google_ip,media_ip,direct_ip"]
    },
    "rule-providers": Object.fromEntries(Object.entries(ruleProviderDefinitions)
      .filter(([name]) => !optionalProviders.has(name))
      .map(([name, provider]) => [name, JSON.parse(JSON.stringify(provider))])),
    "rules": [
      "DST-PORT,5228-5230,直接连接",
      "SUB-RULE,(RULE-SET,telegram_ip,no-resolve),sub-telegram",
      "RULE-SET,ads,REJECT",
      "RULE-SET,proxy@direct,直接连接",
      "SUB-RULE,(RULE-SET,ai),sub-ai",
      "SUB-RULE,(RULE-SET,download),sub-download",
      "SUB-RULE,(RULE-SET,safe),sub-safe",
      "SUB-RULE,(RULE-SET,google),sub-google",
      "SUB-RULE,(RULE-SET,media),sub-media",
      "SUB-RULE,(RULE-SET,proxy-lite),sub-proxy",
      "RULE-SET,direct-lite,直接连接",
      "SUB-RULE,(RULE-SET,safe_ip),sub-safe",
      "SUB-RULE,(RULE-SET,google_ip),sub-google",
      "SUB-RULE,(RULE-SET,media_ip),sub-media",
      "RULE-SET,direct_ip,直接连接",
      quic,
      "MATCH,代理连接"
    ],
    "sub-rules": {
      "sub-telegram": [quic, "MATCH,TELEGRAM"],
      "sub-ai": [quic, "MATCH,国外AI"],
      "sub-download": [quic, "MATCH,下载相关"],
      "sub-safe": [quic, "MATCH,风控安全"],
      "sub-google": [quic, "MATCH,GOOGLE"],
      "sub-media": [quic, "MATCH,海外媒体"],
      "sub-proxy": [quic, "MATCH,代理连接"]
    },
    "proxies": [{ "name": "IPV4优先", "type": "direct", "udp": true, "ip-version": "ipv4-prefer" },{ "name": "IPV6优先", "type": "direct", "udp": true, "ip-version": "ipv6-prefer" },{ "name": "仅IPV4", "type": "direct", "udp": true, "ip-version": "ipv4" },{ "name": "仅IPV6", "type": "direct", "udp": true, "ip-version": "ipv6" }],
    "proxy-groups": [
      { "name": "代理连接", "type": "select", "proxies": ["最低延迟", "故障转移", "香港|故障转移", "台湾|故障转移", "新加坡|故障转移", "日本|故障转移", "美国|故障转移", "德国|故障转移", "英国|故障转移", "荷兰|故障转移", "香港|轮询下载", "新加坡|轮询下载", "日本|轮询下载", "美国|轮询下载"], "include-all-providers": true, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Universal/StreamingSE.png" },
      { "name": "直接连接", "type": "select", "proxies": ["DIRECT", "IPV4优先", "IPV6优先", "仅IPV4", "仅IPV6"], "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Accommodation/Online_Booking.png" },
      { "name": "代理DNS", ...dlAnchor, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Universal/Streaming.png" },
      { "name": "代理QUIC", "type": "select", "proxies": ["PASS-RULE", "REJECT"], "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Google_Suite/Admin.png" },
      { "name": "TELEGRAM", ...dlAnchor, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Social_Media/Telegram.png" },
      { "name": "国外AI", ...dlAnchor, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Fitness/Chat.png" },
      { "name": "下载相关", ...dlAnchor, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Google_Suite/Drive.png" },
      { "name": "风控安全", ...dlAnchor, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Google_Suite/Account.png" },
      { "name": "GOOGLE", ...dlAnchor, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Google_Suite/Google.png" },
      { "name": "海外媒体", ...dlAnchor, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Universal/Video.png" },
      { "name": "最低延迟", "type": "url-test", "tolerance": 30, "include-all-providers": true, "empty-fallback": "REJECT", "hidden": true, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Universal/Auto_Speed.png" },
      { "name": "故障转移", ...fallAnchor, "filter": "(?i)🇭🇰|香港|\\bHK\\b|\\bhongkong\\b|\\bhong\s?kong\\b|🇸🇬|新加坡|狮城|\\bSG\\b|\\bsingapore\\b|🇯🇵|日本|\\bJP\\b|\\bjapan\\b|🇺🇸|美国|\\bUS\\b|\\bunitedstates\\b|\\bunited\s?states\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Universal/Final.png" },
      { "name": "香港|故障转移", ...fallAnchor, "filter": "(?i)🇭🇰|香港|\\bHK\\b|\\bhongkong\\b|\\bhong\\s?kong\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Hong_Kong.png" },
      { "name": "台湾|故障转移", ...fallAnchor, "filter": "(?i)🇹🇼|台湾|\\bTW\\b|\\btaiwan\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Taiwan.png" },
      { "name": "新加坡|故障转移", ...fallAnchor, "filter": "(?i)🇸🇬|新加坡|狮城|\\bSG\\b|\\bsingapore\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Singapore.png" },
      { "name": "日本|故障转移", ...fallAnchor, "filter": "(?i)🇯🇵|日本|\\bJP\\b|\\bjapan\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Japan.png" },
      { "name": "美国|故障转移", ...fallAnchor, "filter": "(?i)🇺🇸|美国|\\bUS\\b|\\bunitedstates\\b|\\bunited\\s?states\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/United_States.png" },
      { "name": "德国|故障转移", ...fallAnchor, "filter": "(?i)🇩🇪|德国|\\bDE\\b|\\bgermany\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Germany.png" },
      { "name": "英国|故障转移", ...fallAnchor, "filter": "(?i)🇬🇧|英国|\\bUK\\b|\\bGB\\b|\\bunitedkingdom\\b|\\bunited\\s?kingdom\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/United_Kingdom.png" },
      { "name": "荷兰|故障转移", ...fallAnchor, "filter": "(?i)🇳🇱|荷兰|\\bNL\\b|\\bnetherlands?\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Netherlands.png" },
      { "name": "香港|轮询下载", ...balAnchor, "filter": "(?i)🇭🇰|香港|\\bHK\\b|\\bhongkong\\b|\\bhong\\s?kong\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Hong_Kong.png" },
      { "name": "新加坡|轮询下载", ...balAnchor, "filter": "(?i)🇸🇬|新加坡|狮城|\\bSG\\b|\\bsingapore\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Singapore.png" },
      { "name": "日本|轮询下载", ...balAnchor, "filter": "(?i)🇯🇵|日本|\\bJP\\b|\\bjapan\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/Japan.png" },
      { "name": "美国|轮询下载", ...balAnchor, "filter": "(?i)🇺🇸|美国|\\bUS\\b|\\bunitedstates\\b|\\bunited\\s?states\\b", "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Rounded_Rectangle/United_States.png" },
      { "name": "GLOBAL", "type": "select", "proxies": ["最低延迟", "故障转移", "香港|故障转移", "台湾|故障转移", "新加坡|故障转移", "日本|故障转移", "美国|故障转移", "德国|故障转移", "英国|故障转移", "荷兰|故障转移", "香港|轮询下载", "新加坡|轮询下载", "日本|轮询下载", "美国|轮询下载", "代理连接", "直接连接", "代理DNS", "代理QUIC", "TELEGRAM", "国外AI", "下载相关", "风控安全", "GOOGLE", "海外媒体"], "include-all-providers": true, "hidden": true, "icon": "https://mihomo.echs.top/img/Hand-Painted-icon/Google_Suite/Browser.png" }
    ]
  };
}


const personalSettings = {
  "ai": {
    "enabled": true,
    "regions": [
      "美国",
      "日本"
    ]
  },
  "dlsite": {
    "enabled": true,
    "defaultGroup": "日本"
  },
  "downloads": {
    "enabled": true,
    "name": "下载更新"
  },
  "oneDrive": true,
  "dnsFollowServices": {
    "ai": true,
    "dlsite": true
  },
  "preserveClientSettings": true,
  "dns": {
    "ecsMode": "resolver-default",
    "directRules": true
  }
};

const personalLists = {
  "microsoft-direct": [
    "DOMAIN,1drv.ms",
    "DOMAIN,learn.microsoft.com",
    "DOMAIN,support.microsoft.com",
    "DOMAIN,account.microsoft.com",
    "DOMAIN,account.live.com",
    "DOMAIN,login.live.com",
    "DOMAIN,login.microsoftonline.com",
    "DOMAIN,logincdn.msauth.net",
    "DOMAIN,graph.microsoft.com",
    "DOMAIN,api.onedrive.com",
    "DOMAIN,oneclient.sfx.ms",
    "DOMAIN,www.office.com",
    "DOMAIN,www.microsoft365.com",
    "DOMAIN,m365.cloud.microsoft",
    "DOMAIN,www.onenote.com",
    "DOMAIN,onenote.cloud.microsoft",
    "DOMAIN,teams.microsoft.com",
    "DOMAIN,code.visualstudio.com",
    "DOMAIN,update.code.visualstudio.com",
    "DOMAIN,marketplace.visualstudio.com",
    "DOMAIN,vscode.dev",
    "DOMAIN,packages.microsoft.com",
    "DOMAIN,www.nuget.org",
    "DOMAIN,api.nuget.org",
    "DOMAIN,registry.npmjs.org",
    "DOMAIN,www.powershellgallery.com",
    "DOMAIN,dot.net",
    "DOMAIN,builds.dotnet.microsoft.com",
    "DOMAIN,www.msftconnecttest.com",
    "DOMAIN,www.msftncsi.com",
    "DOMAIN,www.xbox.com"
  ],
  "academic-direct": [
    "DOMAIN-SUFFIX,cnki.net",
    "DOMAIN-SUFFIX,cnki.com.cn",
    "DOMAIN-SUFFIX,wanfangdata.com.cn",
    "DOMAIN-SUFFIX,cqvip.com",
    "DOMAIN-SUFFIX,sciencedirect.com",
    "DOMAIN-SUFFIX,elsevier.com",
    "DOMAIN-SUFFIX,els-cdn.com",
    "DOMAIN-SUFFIX,scopus.com",
    "DOMAIN-SUFFIX,springer.com",
    "DOMAIN-SUFFIX,springerlink.com",
    "DOMAIN-SUFFIX,springernature.com",
    "DOMAIN-SUFFIX,nature.com",
    "DOMAIN-SUFFIX,wiley.com",
    "DOMAIN-SUFFIX,tandfonline.com",
    "DOMAIN-SUFFIX,sagepub.com",
    "DOMAIN-SUFFIX,oup.com",
    "DOMAIN-SUFFIX,cambridge.org",
    "DOMAIN-SUFFIX,science.org",
    "DOMAIN-SUFFIX,sciencemag.org",
    "DOMAIN-SUFFIX,pnas.org",
    "DOMAIN-SUFFIX,cell.com",
    "DOMAIN-SUFFIX,ieee.org",
    "DOMAIN-SUFFIX,acm.org",
    "DOMAIN-SUFFIX,acs.org",
    "DOMAIN-SUFFIX,rsc.org",
    "DOMAIN-SUFFIX,iop.org",
    "DOMAIN-SUFFIX,aip.org",
    "DOMAIN-SUFFIX,aps.org",
    "DOMAIN-SUFFIX,ascelibrary.org",
    "DOMAIN-SUFFIX,icevirtuallibrary.com",
    "DOMAIN-SUFFIX,geotechniqueletters.com",
    "DOMAIN-SUFFIX,mdpi.com",
    "DOMAIN-SUFFIX,frontiersin.org",
    "DOMAIN-SUFFIX,plos.org",
    "DOMAIN-SUFFIX,biomedcentral.com",
    "DOMAIN-SUFFIX,arxiv.org",
    "DOMAIN-SUFFIX,biorxiv.org",
    "DOMAIN-SUFFIX,medrxiv.org",
    "DOMAIN-SUFFIX,ssrn.com",
    "DOMAIN-SUFFIX,ncbi.nlm.nih.gov",
    "DOMAIN-SUFFIX,doi.org",
    "DOMAIN-SUFFIX,crossref.org",
    "DOMAIN-SUFFIX,orcid.org",
    "DOMAIN-SUFFIX,webofscience.com",
    "DOMAIN-SUFFIX,webofknowledge.com",
    "DOMAIN-SUFFIX,clarivate.com"
  ],
  "extra-direct": [
    "DOMAIN,fsend.cn",
    "DOMAIN-SUFFIX,lsposed.org",
    "DOMAIN-SUFFIX,lsposed.zip",
    "DOMAIN,international-gfe.download.nvidia.com"
  ],
  "downloads": [
    "DOMAIN-SUFFIX,steamcontent.com",
    "DOMAIN-SUFFIX,download.epicgames.com",
    "DOMAIN-SUFFIX,download2.epicgames.com",
    "DOMAIN-SUFFIX,download3.epicgames.com",
    "DOMAIN-SUFFIX,download4.epicgames.com",
    "DOMAIN-SUFFIX,fastly-download.epicgames.com",
    "DOMAIN-SUFFIX,epicgames-download1.akamaized.net",
    "DOMAIN-SUFFIX,dl.delivery.mp.microsoft.com",
    "DOMAIN-SUFFIX,download.windowsupdate.com",
    "DOMAIN-SUFFIX,download.nvidia.com"
  ],
  "onedrive": [
    "PROCESS-NAME,OneDrive.exe",
    "PROCESS-NAME,OneDrive.Sync.Service.exe",
    "PROCESS-NAME,OneDriveStandaloneUpdater.exe",
    "PROCESS-NAME,com.microsoft.skydrive"
  ]
};

// Dynamic region and multiplier menus, based on the nodes actually imported.
function personalNodeRate(name) {
  const match = name.match(
    /(?:^|[^\dA-Za-z.])(\d+(?:\.\d+)?)\s*[*×✕✖⨯⨉x倍](?=$|[^\dA-Za-z.])|(?:[*×✕✖⨯⨉]|(?<![A-Za-z])x)\s*(\d+(?:\.\d+)?)(?=$|[^\dA-Za-z.])/i,
  );
  if (match) return Number(match[1] === undefined ? match[2] : match[1]);
  const labelled = name.match(/(?:倍率|[低高]倍)\s*[:：=]?\s*(\d+(?:\.\d+)?)(?=$|[^\dA-Za-z.])/i);
  return labelled ? Number(labelled[1]) : null;
}

function personalNodeFilter(names) {
  return '^(?:' + names.map(name => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')$';
}

function configurePersonalNodeGroups(config, reservedGroupNames = []) {
  const definitions = [
    ['香港', /🇭🇰|香港|(?<![A-Za-z])HKG?(?![A-Za-z])|hong\s*kong/i],
    ['日本', /🇯🇵|日本|东京|大阪|京都|(?<![A-Za-z])JPN?(?![A-Za-z])|japan/i],
    ['美国', /🇺🇸|美国|纽约|洛杉矶|旧金山|芝加哥|休斯顿|迈阿密|西雅图|波士顿|华盛顿|拉斯维加斯|圣何塞|圣地亚哥|(?<![A-Za-z])USA?(?![A-Za-z])|america|united\s*states/i],
    ['新加坡', /🇸🇬|新加坡|狮城|(?<![A-Za-z])SGP?(?![A-Za-z])|singapore/i],
    ['台湾', /🇹🇼|台湾|台北|高雄|(?<![A-Za-z])TWN?(?![A-Za-z])|taiwan/i],
    ['德国', /🇩🇪|德国|法兰克福|(?<![A-Za-z])DEU?(?![A-Za-z])|germany/i],
    ['英国', /🇬🇧|英国|伦敦|(?<![A-Za-z])(?:UK|GBR?)(?![A-Za-z])|united\s*kingdom/i],
    ['荷兰', /🇳🇱|荷兰|阿姆斯特丹|(?<![A-Za-z])NLD?(?![A-Za-z])|netherlands?/i],
  ];
  const provider = config['proxy-providers']?.['节点'];
  if (!Array.isArray(provider?.payload)) throw new Error('基础配置缺少节点提供器，无法生成动态分组');
  const excluded = provider['exclude-filter'] ? new RegExp(provider['exclude-filter'].replace(/^\(\?i\)/, ''), 'i') : null;
  const nodes = provider.payload.filter(proxy => typeof proxy.name === 'string' &&
    !['direct', 'reject', 'reject-drop', 'pass', 'dns'].includes(String(proxy.type).toLowerCase()) &&
    !(excluded && excluded.test(proxy.name)));
  const regions = Object.create(null);
  for (const [name, pattern] of definitions) regions[name] = [...new Set(nodes.filter(proxy => pattern.test(proxy.name)).map(proxy => proxy.name))];
  const recognized = new Set(Object.values(regions).flat());
  const other = [...new Set(nodes.filter(proxy => !recognized.has(proxy.name)).map(proxy => proxy.name))];
  const low = [], high = [];
  for (const proxy of nodes) {
    const rate = personalNodeRate(proxy.name);
    if (rate !== null ? rate <= 0.5 : /低倍|免费|(?<![A-Za-z])free(?![A-Za-z])/i.test(proxy.name)) low.push(proxy.name);
    if (rate !== null && rate >= 2) high.push(proxy.name);
  }
  const original = config['proxy-groups'];
  const oldRegional = new Set(original.filter(group => /\|(?:故障转移|轮询下载)$/.test(group.name)).map(group => group.name));
  const remaining = original.filter(group => !oldRegional.has(group.name));
  const reserved = new Set([
    ...remaining.map(group => group.name),
    ...(config.proxies || []).map(proxy => proxy.name),
    ...Object.values(config['proxy-providers']).flatMap(entry => (entry.payload || []).map(proxy => proxy.name)),
    'OneDrive', 'DLsite', '下载更新', 'DIRECT', 'REJECT', 'PASS-RULE',
    ...reservedGroupNames,
  ]);
  const allocate = name => {
    let result = name;
    for (let suffix = 1; reserved.has(result); suffix++) result = name + '（分组' + (suffix === 1 ? '' : suffix) + '）';
    reserved.add(result);
    return result;
  };
  const automatic = original.find(group => group.name === '最低延迟');
  const balance = original.find(group => group.type === 'load-balance');
  if (!automatic || !balance) throw new Error('基础配置缺少最低延迟或负载均衡模板');
  const health = provider['health-check'] || {};
  const generated = [], parents = [], buckets = [], regionGroups = Object.create(null);
  const references = Object.create(null);
  function createBucket(label, names, icon, kind) {
    names = [...new Set(names)];
    if (!names.length) return null;
    const parent = allocate(label), auto = allocate(parent + '|最低延迟'), load = allocate(parent + '|负载均衡');
    const common = { use: ['节点'], filter: personalNodeFilter(names), 'empty-fallback': 'REJECT', hidden: true };
    const autoGroup = { ...automatic, ...common, name: auto };
    const loadGroup = { ...balance, ...common, name: load };
    for (const child of [autoGroup, loadGroup]) {
      delete child['include-all-providers']; delete child['include-all']; delete child.proxies;
      for (const field of ['url', 'interval', 'timeout', 'expected-status', 'lazy', 'max-failed-times']) if (health[field] !== undefined) child[field] = health[field];
      if (icon) child.icon = icon;
    }
    generated.push({ name: parent, type: 'select', proxies: [auto, load], use: ['节点'], filter: personalNodeFilter([auto, load, ...names]), 'default-selected': auto, ...(icon ? { icon } : {}) }, autoGroup, loadGroup);
    parents.push(parent);
    buckets.push({ kind, label, parent, children: [auto, load] });
    return parent;
  }
  for (const [region] of definitions) {
    const old = original.find(group => group.name === region + '|故障转移');
    const parent = createBucket(region, regions[region], old?.icon, 'region');
    if (parent) regionGroups[region] = parent;
    references[region + '|故障转移'] = parent;
    references[region + '|轮询下载'] = parent;
  }
  createBucket('其他节点', other, automatic.icon, 'other');
  createBucket('低倍率节点', low, automatic.icon, 'multiplier');
  createBucket('高倍率节点', high, balance.icon, 'multiplier');
  for (const group of remaining) {
    if (!Array.isArray(group.proxies) || !group.proxies.some(name => oldRegional.has(name))) continue;
    const menu = [];
    let inserted = false;
    for (const name of group.proxies) {
      if (oldRegional.has(name)) {
        if (!inserted) { menu.push(...parents); inserted = true; }
      } else menu.push(name);
    }
    group.proxies = [...new Set(menu)];
    if (oldRegional.has(group['default-selected'])) group['default-selected'] = references[group['default-selected']] || group.proxies[0] || 'REJECT';
  }
  config['proxy-groups'] = [...remaining, ...generated];
  return { regions, regionGroups, references, buckets };
}


// Application selectors take priority over broad download, security and media categories.
function configureApplicationGroups(config, nodeGroups, template, options) {
  const enabled = applicationGroups.filter(app => app.existingGroup || options[app.name]);
  const groups = config['proxy-groups'];
  const addProvider = id => {
    if (!ruleProviderDefinitions[id]) throw new Error('Missing rule provider definition: ' + id);
    config['rule-providers'][id] = personalClone(ruleProviderDefinitions[id]);
  };
  const appRules = [], ipRules = [];
  for (const app of enabled) {
    if (!app.existingGroup) {
      const preferred = nodeGroups.regionGroups[app.defaultGroup] || app.defaultGroup;
      const selected = groups.some(group => group.name === preferred) ? preferred : '代理连接';
      groups.push({ ...personalClone(template), name: app.name, proxies: [selected, ...template.proxies.filter(name => name !== selected)], 'default-selected': selected });
    }
    addProvider(app.domain);
    const subRule = 'sub-app-' + app.domain;
    config['sub-rules'][subRule] = ['AND,((NETWORK,udp),(DST-PORT,443)),代理QUIC', 'MATCH,' + app.name];
    const domainRule = 'SUB-RULE,(RULE-SET,' + app.domain + '),' + subRule;
    if (app.name === 'FCM') {
      const portIndex = config.rules.indexOf('DST-PORT,5228-5230,直接连接');
      if (portIndex >= 0) config.rules[portIndex] = 'DST-PORT,5228-5230,FCM';
      const directIndex = config.rules.indexOf('RULE-SET,proxy@direct,直接连接');
      if (directIndex < 0) throw new Error('Missing direct exception rule for FCM insertion');
      config.rules.splice(directIndex, 0, domainRule);
    } else appRules.push(domainRule);
    if (app.ip) {
      addProvider(app.ip);
      ipRules.push('SUB-RULE,(RULE-SET,' + app.ip + ',no-resolve),' + subRule);
    }
    if (app.baseIp) {
      const index = config.rules.findIndex(rule => rule.startsWith('SUB-RULE,(RULE-SET,' + app.baseIp + ')'));
      if (index < 0) throw new Error('Missing application IP rule: ' + app.baseIp);
      config.rules[index] = 'SUB-RULE,(RULE-SET,' + app.baseIp + '),' + subRule;
    }
  }
  const appIndex = config.rules.indexOf('SUB-RULE,(RULE-SET,download),sub-download');
  if (appIndex < 0) throw new Error('Missing aggregate download rule for application insertion');
  config.rules.splice(appIndex, 0, ...appRules);
  const ipIndex = config.rules.findIndex(rule => rule.startsWith('SUB-RULE,(RULE-SET,safe_ip)'));
  if (ipIndex < 0) throw new Error('Missing aggregate IP rules for application insertion');
  config.rules.splice(ipIndex, 0, ...ipRules);
  const global = groups.find(group => group.name === 'GLOBAL');
  if (global) global.proxies = [...new Set([...global.proxies, ...enabled.map(app => app.name)])];
  return enabled;
}

// Resolve application domains through their selected exit, after personal and AI exceptions.
function configureApplicationDns(config, enabled, followServices) {
  if (!enabled.length) return;
  const dns = config.dns;
  const fcm = enabled.filter(app => app.name === 'FCM');
  const other = enabled.filter(app => app.name !== 'FCM');
  const filters = dns['fake-ip-filter'];
  const fcmIndex = filters.indexOf('RULE-SET,proxy@direct,real-ip');
  const appIndex = filters.indexOf('RULE-SET,download,fake-ip');
  if (fcmIndex < 0 || appIndex < 0) throw new Error('Missing DNS classification for application insertion');
  filters.splice(appIndex, 0, ...other.map(app => 'RULE-SET,' + app.domain + ',fake-ip'));
  filters.splice(fcmIndex, 0, ...fcm.map(app => 'RULE-SET,' + app.domain + ',real-ip'));
  if (!followServices) return;
  const policies = {};
  const insert = apps => {
    for (const app of apps) {
      const resolvers = app.name === 'FCM' ? dns['direct-nameserver'] : dns.nameserver;
      policies['rule-set:' + app.domain] = resolvers.map(address => personalDnsThroughGroup(address, app.name));
    }
  };
  let appsInserted = false;
  for (const [key, value] of Object.entries(dns['nameserver-policy'])) {
    if (key === 'rule-set:proxy@direct') insert(fcm);
    if (key.startsWith('rule-set:') && key.slice(9).split(',').includes('download')) {
      const names = key.slice(9).split(',');
      if (names.includes('ai')) policies['rule-set:ai'] = value;
      insert(other);
      appsInserted = true;
      const remaining = names.filter(name => name !== 'ai');
      if (remaining.length) policies['rule-set:' + remaining.join(',')] = value;
    } else policies[key] = value;
  }
  if (!appsInserted) throw new Error('Missing aggregate DNS policy for application insertion');
  dns['nameserver-policy'] = policies;
}


// Group menus and icons follow the service order, then region and multiplier.
function configureGroupPresentation(config, nodeGroups) {
  const qure = name => 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/' + name + '.png';
  const lige = name => 'https://fastly.jsdelivr.net/gh/lige47/QuanX-icon-rule@main/icon/' + name + '.png';
  const icons = Object.assign(Object.create(null), {
    '代理连接': qure('Proxy'),
    '直接连接': qure('Direct'),
    '代理DNS': qure('Server'),
    '代理QUIC': qure('Static'),
    '国外AI': qure('ChatGPT'),
    'YouTube': qure('YouTube'),
    'GOOGLE': qure('Google_Search'),
    'TELEGRAM': qure('Telegram'),
    'Microsoft': qure('Microsoft'),
    'OneDrive': qure('OneDrive'),
    'Apple': qure('Apple'),
    'Steam': qure('Steam'),
    'Twitter': qure('Twitter'),
    'Meta': lige('04ProxySoft/meta'),
    'Line': qure('Line'),
    'Netflix': qure('Netflix'),
    'PikPak': lige('03CNSoft/pikpak'),
    'EHentai': lige('04ProxySoft/exhentai'),
    'DLsite': 'https://www.dlsite.com/modpub/images/web/common/apple_touch_icon_152x152.png',
    'FCM': 'https://fastly.jsdelivr.net/gh/MiToverG422/Qure@master/IconSet/Color/fcm.png',
    '下载更新': qure('App_Store'),
    '下载相关': qure('Download'),
    '风控安全': qure('Lock'),
    '海外媒体': qure('ForeignMedia'),
    '最低延迟': qure('Auto'),
    '故障转移': qure('Available'),
    'GLOBAL': qure('Global'),
  });
  const regionIcons = Object.assign(Object.create(null), {
    '香港': qure('Hong_Kong'),
    '日本': qure('Japan'),
    '美国': qure('United_States'),
    '新加坡': qure('Singapore'),
    '台湾': qure('Taiwan'),
    '德国': qure('Germany'),
    '英国': qure('United_Kingdom'),
    '荷兰': lige('01Country/Netherlands'),
  });
  const order = [
    '代理连接', '直接连接', '代理DNS', '代理QUIC',
    '国外AI', 'YouTube', 'GOOGLE', 'TELEGRAM', 'Microsoft', 'OneDrive',
    'Apple', 'Steam', 'Twitter', 'Meta', 'Line', 'Netflix', 'PikPak',
    'EHentai', 'DLsite', 'FCM', '下载更新', '下载相关', '风控安全', '海外媒体',
  ];
  if (typeof personalSettings !== 'undefined' && personalSettings.downloads?.name) {
    const customDownload = personalSettings.downloads.name;
    if (!order.includes(customDownload)) order.splice(order.indexOf('下载相关'), 0, customDownload);
    icons[customDownload] = qure('App_Store');
  }
  const groups = config['proxy-groups'];
  const byName = new Map(groups.map(group => [group.name, group]));
  const buckets = nodeGroups.buckets || [];
  const bucketNames = new Set(buckets.flatMap(bucket => [bucket.parent, ...bucket.children]));
  const hiddenLast = ['最低延迟', '故障转移', 'GLOBAL'];

  // Keep additional services before the node menus without guessing from names.
  for (const group of groups) {
    if (!order.includes(group.name) && !bucketNames.has(group.name) && !hiddenLast.includes(group.name)) order.push(group.name);
    if (icons[group.name]) group.icon = icons[group.name];
    else if (!group.icon || group.icon.includes('mihomo.echs.top/')) group.icon = qure('Stack');
  }
  for (const kind of ['region', 'other', 'multiplier']) {
    for (const bucket of buckets.filter(item => item.kind === kind)) {
      order.push(bucket.parent, ...bucket.children);
      const parent = byName.get(bucket.parent);
      if (parent) parent.icon = bucket.kind === 'region'
        ? regionIcons[bucket.label] || qure('World_Map')
        : bucket.kind === 'other' ? qure('World_Map')
          : qure(bucket.label === '低倍率节点' ? 'Available_1' : 'Airport');
      for (const [index, name] of bucket.children.entries()) {
        const child = byName.get(name);
        if (child) {
          child.hidden = true;
          child.icon = qure(index === 0 ? 'Auto' : 'Round_Robin');
        }
      }
    }
  }
  order.push(...hiddenLast);
  for (const name of hiddenLast) if (byName.has(name)) byName.get(name).hidden = true;
  const rank = new Map(order.map((name, index) => [name, index]));
  const compare = (left, right) => (rank.get(left) ?? order.length) - (rank.get(right) ?? order.length);
  groups.sort((left, right) => compare(left.name, right.name));
  const global = byName.get('GLOBAL');
  if (Array.isArray(global?.proxies)) {
    // Reordering the menu must not silently change its initial selected route.
    if (global['default-selected'] === undefined && global.proxies.length) global['default-selected'] = global.proxies[0];
    global.proxies.sort(compare);
  }
  return config;
}


// Keep DNS classification consistent with the personal traffic rules.
// Run before importing subscription DNS, whose explicit ECS must be preserved.
function withoutForcedEcs(address) {
  if (typeof address !== 'string' || !address.includes('#')) return address;
  const split = address.indexOf('#');
  const parameters = address.slice(split + 1).split('&').filter(part => {
    const key = part.split('=')[0].toLowerCase();
    return key !== 'ecs' && key !== 'ecs-override';
  });
  return address.slice(0, split) + (parameters.length ? '#' + parameters.join('&') : '');
}

function patchDnsExperience(config, lists, options, downloadEnabled, downloadGroup) {
  const settings = options || {};
  const mode = settings.ecsMode || 'resolver-default';
  if (!['resolver-default', 'upstream'].includes(mode)) throw new Error('未知 ECS 模式：' + mode);
  const dns = config.dns;
  const mapResolvers = value => Array.isArray(value) ? value.map(withoutForcedEcs) : withoutForcedEcs(value);
  if (mode === 'resolver-default') {
    for (const key of ['nameserver', 'direct-nameserver']) if (dns[key]) dns[key] = mapResolvers(dns[key]);
    for (const [key, value] of Object.entries(dns['nameserver-policy'] || {})) dns['nameserver-policy'][key] = mapResolvers(value);
  }
  if (settings.directRules === false) return config;
  const payload = entries => [...new Set(entries.map(rule => {
    const [type, domain] = rule.split(',');
    if (type === 'DOMAIN') return domain;
    if (type === 'DOMAIN-SUFFIX') return '+.' + domain;
    throw new Error('DNS 域名清单包含不支持的规则类型：' + type);
  }))];
  const providers = config['rule-providers'];
  if (providers['personal-direct'] || providers['personal-download']) throw new Error('个人 DNS 规则集与基础配置重名');
  providers['personal-direct'] = { type: 'inline', behavior: 'domain', payload: payload([...lists['microsoft-direct'], ...lists['extra-direct'], ...lists['academic-direct']]) };
  if (downloadEnabled) providers['personal-download'] = { type: 'inline', behavior: 'domain', payload: payload(lists.downloads) };
  const filterIndex = dns['fake-ip-filter'].indexOf('RULE-SET,ads,fake-ip');
  if (dns['fake-ip-filter-mode'] !== 'rule' || filterIndex < 0) throw new Error('基础配置的 Fake-IP 规则不支持个人 DNS 分类');
  dns['fake-ip-filter'].splice(filterIndex + 1, 0,
    ...(downloadEnabled ? ['RULE-SET,personal-download,fake-ip'] : []),
    'RULE-SET,personal-direct,real-ip');
  const policies = {};
  let inserted = false;
  for (const [key, value] of Object.entries(dns['nameserver-policy'])) {
    policies[key] = value;
    if (key !== 'rule-set:ads') continue;
    if (downloadEnabled) {
      // A manually switched download keeps its domain and resolves through the
      // same selected group. The domestic resolver endpoints remain reachable
      // for its default direct route.
      policies['rule-set:personal-download'] = dns['direct-nameserver'].map(address => {
        const [base, ...suffix] = address.split('#');
        const parameters = suffix.join('&').split('&').filter(part => part.includes('='));
        return base + '#' + [downloadGroup, ...parameters].join('&');
      });
    }
    policies['rule-set:personal-direct'] = [...dns['direct-nameserver']];
    inserted = true;
  }
  if (!inserted) throw new Error('基础配置缺少广告 DNS 规则，无法确定个人 DNS 顺序');
  dns['nameserver-policy'] = policies;
  return config;
}


// Private subscription DNS and hosts preservation for the Echsfxy configuration.
const personalDnsCommonDnsList = [
  // IPv4（国内）
  '223.5.5.5',
  '223.6.6.6',
  '119.29.29.29',
  '1.12.12.12',
  '120.53.53.53',
  '114.114.114.114',
  '180.76.76.76',
  '1.2.4.8',
  '116.116.116.116',
  '101.226.4.6',
  '123.125.81.6',
  '180.184.1.1',
  '180.184.2.2',

  // IPv6（国内）
  '2400:3200::1',
  '2400:3200:baba::1',
  '2402:4e00::',
  '2400:da00::6666',

  // IPv4（国外）
  '1.1.1.1',
  '1.0.0.1',
  '8.8.8.8',
  '8.8.4.4',
  '9.9.9.9',
  '149.112.112.112',
  '208.67.222.222',
  '208.67.220.220',
  '94.140.14.14',
  '94.140.15.15',
  '76.76.2.0',
  '76.76.10.0',
  '185.228.168.9',
  '185.228.169.9',
  '77.88.8.8',
  '77.88.8.1',
  '156.154.70.1',
  '156.154.71.1',

  // IPv6（国外）
  '2606:4700:4700::1111',
  '2606:4700:4700::1001',
  '2001:4860:4860::8888',
  '2001:4860:4860::8844',
  '2620:fe::fe',
  '2620:fe::9',
  '2620:119:35::35',
  '2620:119:53::53',
  '2a10:50c0::bad1:ff',
  '2a10:50c0::bad2:ff',
  '2a10:50c0::ad1:ff',
  '2a10:50c0::ad2:ff',
  '2a0d:2a00:1::2',
  '2a0d:2a00:2::2',
  '2a02:6b8::feed:0ff',
  '2a02:6b8:0:1::feed:0ff',
  '2610:a1:1018::1',
  '2610:a1:1019::1',

  // 公共解析服务的主机名及其子域
  'alidns.com',
  'doh.pub',
  'dot.pub',
  'dns.pub',
  'dnspod.cn',
  'dnspod.com',
  'dns.baidu.com',
  'dns.google',
  'dns.cloudflare.com',
  'cloudflare-dns.com',
  'quad9.net',
  'opendns.com',
  'nextdns.io',
  'adguard.com',
  'adguard-dns.com',
  'dns.apple.com',
  'one.one.one.one',
];

// 展开 IPv6 后按地址比较，DNS 路径、参数及相似域名不参与公共解析器判定。
function personalDnsNormalizeDnsHost(host) {
  host = host.toLowerCase().replace(/^\[|\]$/g, '');
  if (!host.includes(':')) return host;
  const parts = host.split('::');
  if (parts.length > 2) return host;
  const left = parts[0] ? parts[0].split(':') : [];
  const right = parts.length > 1 && parts[1] ? parts[1].split(':') : [];
  const missing = 8 - left.length - right.length;
  const words = parts.length === 2 && missing > 0 ? [...left, ...Array(missing).fill('0'), ...right] : left;
  return words.length === 8 && words.every((word) => /^[0-9a-f]{1,4}$/.test(word))
    ? words.map((word) => parseInt(word, 16).toString(16)).join(':')
    : host;
}

function personalDnsParseDnsEndpoint(value) {
  const address = String(value).trim().split('#')[0];
  const schemeMatch = address.match(/^([a-z][a-z0-9+.-]*):\/\//i);
  const scheme = schemeMatch ? schemeMatch[1].toLowerCase() : 'udp';
  let authority = (schemeMatch ? address.slice(schemeMatch[0].length) : address).split(/[/?]/)[0];
  authority = authority.slice(authority.lastIndexOf('@') + 1);
  const bracket = authority.match(/^\[([^\]]+)\](?::(\d+))?$/);
  const hostPort = authority.match(/^([^:]+):(\d+)$/);
  const host = bracket ? bracket[1] : hostPort ? hostPort[1] : authority;
  const port = bracket ? bracket[2] : hostPort ? hostPort[2] : undefined;
  return {
    host: personalDnsNormalizeDnsHost(host),
    port: Number(port || { https: 443, http: 80, tls: 853, quic: 853 }[scheme] || 53),
    scheme,
  };
}

const personalDnsCommonDnsHosts = personalDnsCommonDnsList.map(personalDnsNormalizeDnsHost);
function personalDnsIsPublicDns(dns) {
  const { host, scheme } = personalDnsParseDnsEndpoint(dns);
  if (scheme === 'system' || host === 'system') return true;
  return personalDnsCommonDnsHosts.some(
    (known) => host === known || (!known.includes(':') && !/^\d/.test(known) && host.endsWith(`.${known}`)),
  );
}

function personalDnsCreateHostsLookup(hosts) {
  const makeNode = () => ({ children: new Map(), value: undefined });
  const root = makeNode();
  const insert = (parts, value) => {
    let node = root;
    for (let index = parts.length - 1; index >= 0; index--) {
      if (!node.children.has(parts[index])) node.children.set(parts[index], makeNode());
      node = node.children.get(parts[index]);
    }
    node.value = value;
  };
  for (const [pattern, value] of Object.entries(hosts)) {
    const values = (Array.isArray(value) ? value : [value]).filter((item) => typeof item === 'string' && item.trim());
    if (!values.length) continue;
    const parts = pattern.toLowerCase().split('.');
    if (parts[0] === '+') {
      insert(parts.slice(1), values);
      parts[0] = '';
    }
    insert(parts, values);
  }
  const search = (node, parts, index) => {
    if (!node) return undefined;
    if (index < 0) return node.value;
    return (
      search(node.children.get(parts[index]), parts, index - 1) ||
      search(node.children.get('*'), parts, index - 1) ||
      node.children.get('')?.value
    );
  };
  return (domain) => {
    const parts = domain.toLowerCase().split('.');
    return search(root, parts, parts.length - 1);
  };
}

/**
 * 判断域名规则（精确/通配）是否匹配节点域名集合，忽略大小写
 */
function personalDnsMatchDomainPattern(pattern, domains) {
  pattern = pattern.toLowerCase();

  // 精确匹配
  if (!pattern.includes('*') && !pattern.startsWith('+.') && !pattern.startsWith('.')) {
    return typeof domains === 'string'
      ? domains.toLowerCase() === pattern
      : [...domains].some((d) => d.toLowerCase() === pattern);
  }

  // 通配匹配：统一转为数组遍历（字符串时直接构建单元素数组，避免 Set 中转）
  const domainList = typeof domains === 'string' ? [domains.toLowerCase()] : [...domains].map((d) => d.toLowerCase());

  // +.example.com
  if (pattern.startsWith('+.')) {
    const suffix = pattern.slice(2);
    return domainList.some((domain) => domain === suffix || domain.endsWith(`.${suffix}`));
  }

  // .example.com
  if (pattern.startsWith('.')) {
    const suffix = pattern.slice(1);
    return domainList.some((domain) => domain !== suffix && domain.endsWith(`.${suffix}`));
  }

  // *.example.com、example.*.com 等
  const patternParts = pattern.split('.');
  return domainList.some((domain) => {
    const domainParts = domain.split('.');
    return (
      patternParts.length === domainParts.length &&
      patternParts.every((part, index) => part === '*' || part === domainParts[index])
    );
  });
}

/**
 * 单地址 hosts 改写为节点 server；多地址保存为节点精确 hosts，由内核按 IP 偏好选择。
 * 地址改写保留 TLS 身份；域名映射循环会报错。
 */
function personalDnsApplyHostsToProxies(proxies, hosts, retainedHosts = {}) {
  if (!hosts || typeof hosts !== 'object' || Array.isArray(hosts)) return proxies;
  const lookup = personalDnsCreateHostsLookup(hosts);
  const cache = new Map();
  const resolve = (server) => {
    const key = server.toLowerCase();
    if (cache.has(key)) return cache.get(key);
    const seen = new Set();
    let current = server;
    while (true) {
      const domain = current.toLowerCase();
      if (seen.has(domain)) throw new Error(`hosts 域名映射存在循环：${server}`);
      seen.add(domain);
      const values = lookup(domain);
      if (!values) {
        const result = { server: current };
        cache.set(key, result);
        return result;
      }
      if (values.length > 1) {
        const result = { addresses: [...values] };
        cache.set(key, result);
        return result;
      }
      current = values[0];
    }
  };
  return proxies.map((proxy) => {
    if (typeof proxy.server !== 'string') return proxy;
    const resolved = resolve(proxy.server);
    if (resolved.addresses) {
      retainedHosts[proxy.server] = [...resolved.addresses];
      return proxy;
    }
    if (resolved.server === proxy.server) return proxy;
    // WS、gRPC 等传输及插件可能从 server 派生 Host/authority，交由 hosts 保留原始传输身份。
    if ((proxy.network && proxy.network !== 'tcp') || proxy.plugin) {
      retainedHosts[proxy.server] = resolved.server;
      return proxy;
    }
    const mapped = { ...proxy, server: resolved.server };
    const type = String(proxy.type || '').toLowerCase();
    const usesTls = proxy.tls || ['trojan', 'hysteria', 'hysteria2', 'tuic', 'anytls'].includes(type);
    const field = type === 'vmess' || type === 'vless' ? 'servername' : 'sni';
    if (usesTls && !proxy[field]) mapped[field] = proxy.server;
    return mapped;
  });
}

// Replace only the routing selector; transport/ECS parameters remain unchanged.
function personalDnsThroughGroup(value, group) {
  if (typeof value !== 'string' || !value.trim()) return '';
  const [base, ...suffixes] = value.trim().split('#');
  const parameters = suffixes.join('&').split('&').filter((part) => part.includes('='));
  return base + '#' + [group, ...parameters].join('&');
}

/**
 * Add subscription-specific node DNS/hosts without replacing Echsfxy's general
 * resolvers, prefer-h3, fake-IP policy or other network settings. Returns a new
 * configuration; neither input is mutated. All inputs are plain JSON data.
 */
function patchPersonalDns(originalSubscription, echConfig, settings = {}, groupNames = {}) {
  const object = (value) => value && typeof value === 'object' && !Array.isArray(value) ? value : {};
  const values = (value) => (Array.isArray(value) ? value : [value]).filter((item) => typeof item === 'string' && item.trim());
  const copy = (value) => JSON.parse(JSON.stringify(value));
  const original = object(originalSubscription);
  const originDns = object(original.dns);
  const dns = { ...object(echConfig.dns) };
  const next = { ...echConfig, dns };
  const directGroup = groupNames.direct || 'DIRECT';
  const collectProxies = (config) => [
    ...(Array.isArray(config.proxies) ? config.proxies : []),
    ...Object.values(object(config['proxy-providers'])).flatMap((provider) =>
      provider && Array.isArray(provider.payload) ? provider.payload : []),
  ];
  const nodeDomains = new Set(collectProxies(original)
    .filter((proxy) => proxy && typeof proxy.server === 'string')
    .map((proxy) => proxy.server.toLowerCase()));

  const listen = typeof originDns.listen === 'string' && originDns.listen.trim()
    ? personalDnsParseDnsEndpoint(originDns.listen) : null;
  const localListener = (value) => {
    if (!listen) return false;
    const endpoint = personalDnsParseDnsEndpoint(value);
    if (!['udp', 'tcp'].includes(endpoint.scheme) || endpoint.port !== listen.port) return false;
    return endpoint.host === listen.host ||
      (listen.host === '0.0.0.0' && endpoint.host === '127.0.0.1') ||
      (listen.host === '0:0:0:0:0:0:0:0' && endpoint.host === '0:0:0:0:0:0:0:1');
  };
  const originNodeResolvers = values(originDns['proxy-server-nameserver']);
  const retainedHosts = {};
  if (originNodeResolvers.length === 1 && localListener(originNodeResolvers[0])) {
    if (Array.isArray(next.proxies)) {
      next.proxies = personalDnsApplyHostsToProxies(next.proxies, original.hosts, retainedHosts);
    }
    if (next['proxy-providers']) {
      next['proxy-providers'] = Object.fromEntries(Object.entries(next['proxy-providers']).map(([name, provider]) => [
        name,
        Array.isArray(provider.payload)
          ? { ...provider, payload: personalDnsApplyHostsToProxies(provider.payload, original.hosts, retainedHosts) }
          : provider,
      ]));
    }
  }
  next.hosts = { ...object(original.hosts), ...object(echConfig.hosts), ...retainedHosts };
  for (const proxy of collectProxies(next)) {
    if (proxy && typeof proxy.server === 'string') nodeDomains.add(proxy.server.toLowerCase());
  }
  for (const value of Object.values(retainedHosts).flatMap(values)) nodeDomains.add(value.toLowerCase());
  const matchesNode = (pattern) => !pattern.startsWith('rule-set:') && personalDnsMatchDomainPattern(pattern, nodeDomains);
  let importedHttpsWithoutForcedH3 = false;
  const sanitize = (value, privateOnly = false) => [...new Set(values(value)
    .filter((address) => !localListener(address) && (!privateOnly || !personalDnsIsPublicDns(address)))
    .map((address) => {
      let forceH3 = false;
      for (const part of address.split('#').slice(1).join('&').split('&')) {
        const equals = part.indexOf('=');
        if (part.slice(0, equals).trim() === 'h3') forceH3 = part.slice(equals + 1).trim() === 'true';
      }
      if (personalDnsParseDnsEndpoint(address).scheme === 'https' && !forceH3) importedHttpsWithoutForcedH3 = true;
      return personalDnsThroughGroup(address, directGroup);
    }))];
  const originalPolicy = object(originDns['nameserver-policy']);
  const explicitPolicy = object(originDns['proxy-server-nameserver-policy']);
  const nodePolicy = { ...object(dns['proxy-server-nameserver-policy']) };
  // Echsfxy already copied these keys but removed their parameters. Replace them
  // from the original input, including any renamed rule-set dependencies.
  for (const pattern of Object.keys(explicitPolicy)) delete nodePolicy[pattern];
  const inheritedPrivate = [];
  for (const [pattern, addresses] of Object.entries(originalPolicy)) {
    if (!matchesNode(pattern)) continue;
    const cleaned = sanitize(addresses, true);
    if (!cleaned.length) continue;
    nodePolicy[pattern] = Array.isArray(addresses) ? cleaned : cleaned[0];
    inheritedPrivate.push(...cleaned);
  }

  const originalProviders = object(original['rule-providers']);
  const ruleProviders = { ...object(next['rule-providers']) };
  const copiedProviders = new Map();
  const validGroups = new Set(['DIRECT', 'REJECT', directGroup,
    ...(next['proxy-groups'] || []).map((group) => group.name)]);
  let copiedRuleProvider = false;
  const copyProvider = (sourceName) => {
    if (copiedProviders.has(sourceName)) return copiedProviders.get(sourceName);
    const provider = originalProviders[sourceName];
    if (!provider) return ruleProviders[sourceName] && ['domain', 'classical'].includes(ruleProviders[sourceName].behavior) ? sourceName : null;
    if (!['domain', 'classical'].includes(provider.behavior)) return null;
    let name = sourceName === '__proto__' ? 'personal-dns-' + sourceName : sourceName;
    for (let suffix = 1; Object.prototype.hasOwnProperty.call(ruleProviders, name); suffix++) {
      name = 'personal-dns-' + sourceName + (suffix === 1 ? '' : '-' + suffix);
    }
    const copied = copy(provider);
    if (copied.type === 'http') {
      const extension = ['mrs', 'text'].includes(copied.format) ? copied.format : 'yaml';
      const paths = new Set(Object.values(ruleProviders).map((entry) => entry.path));
      const stem = './rules/personal-dns/' + encodeURIComponent(name);
      copied.path = stem + '.' + extension;
      for (let index = 2; paths.has(copied.path); index++) copied.path = stem + '-' + index + '.' + extension;
    }
    if (copied.proxy && !validGroups.has(copied.proxy)) copied.proxy = directGroup;
    ruleProviders[name] = copied;
    copiedProviders.set(sourceName, name);
    copiedRuleProvider = true;
    return name;
  };
  for (const [pattern, addresses] of Object.entries(explicitPolicy)) {
    const cleaned = sanitize(addresses);
    if (!cleaned.length) continue;
    let key = pattern;
    if (pattern.startsWith('rule-set:')) {
      const names = pattern.slice(9).split(',').map((name) => copyProvider(name.trim())).filter(Boolean);
      if (!names.length) continue;
      key = 'rule-set:' + [...new Set(names)].join(',');
    }
    nodePolicy[key] = Array.isArray(addresses) ? cleaned : cleaned[0];
    if (matchesNode(pattern)) inheritedPrivate.push(...sanitize(addresses, true));
  }
  if (copiedRuleProvider) next['rule-providers'] = ruleProviders;
  if (Object.keys(nodePolicy).length) dns['proxy-server-nameserver-policy'] = nodePolicy;
  else delete dns['proxy-server-nameserver-policy'];

  const explicitResolvers = sanitize(originNodeResolvers);
  const privateResolvers = [...new Set(inheritedPrivate)];
  if (explicitResolvers.length || privateResolvers.length) {
    dns['proxy-server-nameserver'] = [...new Set([...explicitResolvers, ...privateResolvers])];
  } else if (originNodeResolvers.some(localListener)) {
    // The imported local DNS listener is not present in the generated config.
    dns['proxy-server-nameserver'] = copy(dns['direct-nameserver'] || dns['default-nameserver'] || []);
  }
  // Mihomo only handles h3=true as a per-resolver override; h3=false does not
  // cancel prefer-h3. Preserve the source transport preference when importing
  // node HTTPS resolvers, while leaving configurations without them unchanged.
  if (dns['prefer-h3'] === true && originDns['prefer-h3'] !== true && importedHttpsWithoutForcedH3) {
    dns['prefer-h3'] = false;
  }

  // Preserve only node-specific real-IP exceptions when importing a blacklist
  // into Echsfxy's ordered fake-IP rules, rather than widening service bypasses.
  const filters = values(originDns['fake-ip-filter']);
  const realIpNodes = [...nodeDomains].filter((domain) => {
    if (domain.includes(':') || /^\d+\.\d+\.\d+\.\d+$/.test(domain)) return false;
    return filters.some((filter) => {
      if (originDns['fake-ip-filter-mode'] !== 'rule') return personalDnsMatchDomainPattern(filter, domain);
      const [type, value, action] = filter.split(',');
      return action === 'real-ip' && ((type === 'DOMAIN' && domain === value.toLowerCase()) ||
        (type === 'DOMAIN-SUFFIX' && personalDnsMatchDomainPattern('+.' + value, domain)));
    });
  });
  if (realIpNodes.length) {
    const additions = dns['fake-ip-filter-mode'] === 'rule'
      ? realIpNodes.map((domain) => 'DOMAIN,' + domain + ',real-ip') : realIpNodes;
    dns['fake-ip-filter'] = [...new Set([...additions, ...values(dns['fake-ip-filter'])])];
  }

  const follow = settings.dnsFollowServices;
  const servicePolicies = {};
  for (const service of ['ai', 'dlsite']) {
    const enabled = follow === true || (follow && follow[service]);
    const group = groupNames[service];
    if (!enabled || !group || !validGroups.has(group) || !ruleProviders[service]) continue;
    servicePolicies[service] = values(dns.nameserver).map((address) => personalDnsThroughGroup(address, group));
  }
  if (Object.keys(servicePolicies).length) {
    const policies = {};
    const inserted = new Set();
    for (const [pattern, addresses] of Object.entries(object(dns['nameserver-policy']))) {
      if (!pattern.startsWith('rule-set:')) {
        policies[pattern] = addresses;
        continue;
      }
      // DLsite is an early personal route. Its domains also occur in proxy-lite,
      // so appending its DNS policy after the upstream sets would never win.
      const policySets = pattern.slice(9).split(',').map((name) => name.trim());
      if (servicePolicies.dlsite && !inserted.has('dlsite') &&
          policySets.some((name) => !['ads', 'personal-download', 'personal-direct'].includes(name))) {
        policies['rule-set:dlsite'] = servicePolicies.dlsite;
        inserted.add('dlsite');
      }
      const remaining = [];
      for (const name of pattern.slice(9).split(',').map((name) => name.trim())) {
        if (servicePolicies[name]) {
          policies['rule-set:' + name] = servicePolicies[name];
          inserted.add(name);
        } else remaining.push(name);
      }
      if (remaining.length) policies['rule-set:' + remaining.join(',')] = addresses;
    }
    for (const [name, addresses] of Object.entries(servicePolicies)) {
      if (!inserted.has(name)) policies['rule-set:' + name] = addresses;
    }
    dns['nameserver-policy'] = policies;
  }
  return next;
}



// Apply personal service, grouping and DNS settings to the base configuration.
const Compatible_With_Bettbox = { ruleOptionsEnable: true };
const ruleOptionsEnable = {
  ...Object.fromEntries(applicationGroups.filter(app => !app.existingGroup).map(app => [app.name, app.enabled])),
  OneDrive: personalSettings.oneDrive,
  DLsite: personalSettings.dlsite.enabled,
  AI固定出口: personalSettings.ai.enabled,
  大流量下载直连: personalSettings.downloads.enabled,
  DNS跟随服务: true,
};

function personalClone(value) {
  return JSON.parse(JSON.stringify(value));
}

function main(subscription) {
  if (!subscription || !Array.isArray(subscription.proxies) || !subscription.proxies.length) throw new Error('需要包含 proxies 的订阅配置');
  let config = buildBaseConfig(personalClone(subscription));
  const nodeGroups = configurePersonalNodeGroups(config, [personalSettings.downloads.name, ...applicationGroups.map(app => app.name)]);
  const groups = config['proxy-groups'];
  const required = ['直接连接', '代理连接', '国外AI'];
  for (const name of required) if (!groups.some(group => group.name === name)) throw new Error('基础策略组已变化，需要检查个人配置：' + name);
  const aiGroup = groups.find(group => group.name === '国外AI');
  const originalService = personalClone(aiGroup);
  const extraGroups = [];
  const earlyRules = [];

  if (ruleOptionsEnable.OneDrive) {
    extraGroups.push({ name: 'OneDrive', type: 'select', proxies: ['直接连接', '代理连接'] });
    for (const rule of personalLists.onedrive) earlyRules.push(rule + ',OneDrive');
    config['find-process-mode'] = 'strict';
  }
  if (ruleOptionsEnable.大流量下载直连) {
    extraGroups.push({ name: personalSettings.downloads.name, type: 'select', proxies: ['直接连接', '代理连接', '下载相关'] });
    for (const rule of personalLists.downloads) earlyRules.push(rule + ',' + personalSettings.downloads.name);
  }
  for (const key of ['microsoft-direct', 'extra-direct', 'academic-direct']) for (const rule of personalLists[key]) earlyRules.push(rule + ',直接连接');

  if (ruleOptionsEnable.AI固定出口) {
    const candidates = [];
    for (const region of personalSettings.ai.regions) {
      for (const name of nodeGroups.regions[region] || []) if (!candidates.includes(name)) candidates.push(name);
    }
    aiGroup.type = 'select';
    aiGroup.proxies = ['REJECT'];
    // Provider nodes must be referenced through use, not the top-level proxies list.
    // Match names exactly so an update cannot add a different region to this group.
    aiGroup.use = ['节点'];
    aiGroup.filter = '^(?:' + ['REJECT', ...candidates].map(name => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')$';
    aiGroup['default-selected'] = 'REJECT';
    delete aiGroup['include-all-providers'];
    delete aiGroup['include-all'];
  }
  if (ruleOptionsEnable.DLsite) {
    const configured = personalSettings.dlsite.defaultGroup;
    const preferred = nodeGroups.regionGroups[configured] || nodeGroups.references[configured] || configured;
    const defaultGroup = groups.some(group => group.name === preferred) ? preferred : 'REJECT';
    const group = { ...originalService, name: 'DLsite', proxies: [defaultGroup, ...originalService.proxies.filter(name => name !== defaultGroup)], 'default-selected': defaultGroup };
    const preferredGroup = groups.find(item => item.name === defaultGroup);
    if (preferredGroup?.icon) group.icon = preferredGroup.icon;
    extraGroups.push(group);
    if (!ruleProviderDefinitions.dlsite) throw new Error('Missing rule provider definition: dlsite');
    config['rule-providers'].dlsite = personalClone(ruleProviderDefinitions.dlsite);
    earlyRules.push('RULE-SET,dlsite,DLsite');
  }
  const insertion = config.rules.indexOf('RULE-SET,ads,REJECT');
  if (insertion < 0) throw new Error('基础规则顺序已变化，需要检查个人规则插入位置');
  config.rules.splice(insertion + 1, 0, ...earlyRules);
  if (ruleOptionsEnable.AI固定出口) {
    const aiRule = config.rules.indexOf('SUB-RULE,(RULE-SET,ai),sub-ai');
    if (aiRule < 0) throw new Error('基础 AI 规则已变化，需要检查固定出口');
    // Mihomo can skip a selected node without UDP support. Stop before another
    // service or the catch-all can send this traffic through a different exit.
    config.rules.splice(aiRule + 1, 0, 'AND,((NETWORK,UDP),(RULE-SET,ai)),REJECT');
  }
  const aiIndex = groups.indexOf(aiGroup);
  groups.splice(aiIndex + 1, 0, ...extraGroups);
  const global = groups.find(group => group.name === 'GLOBAL');
  if (global) global.proxies.push(...extraGroups.map(group => group.name));
  const enabledApps = configureApplicationGroups(config, nodeGroups, originalService, ruleOptionsEnable);

  const dnsSettings = { dnsFollowServices: ruleOptionsEnable.DNS跟随服务 ? { ai: personalSettings.dnsFollowServices.ai && ruleOptionsEnable.AI固定出口, dlsite: personalSettings.dnsFollowServices.dlsite && ruleOptionsEnable.DLsite } : false };
  config = patchDnsExperience(config, personalLists, personalSettings.dns, ruleOptionsEnable.大流量下载直连, personalSettings.downloads.name);
  config = patchPersonalDns(subscription, config, dnsSettings, { direct: '直接连接', proxy: '代理连接', ai: '国外AI', dlsite: 'DLsite' });
  configureApplicationDns(config, enabledApps, ruleOptionsEnable.DNS跟随服务);
  configureGroupPresentation(config, nodeGroups);
  if (personalSettings.preserveClientSettings) {
    for (const key of ['port', 'socks-port', 'mixed-port', 'redir-port', 'tproxy-port', 'allow-lan', 'bind-address', 'tun', 'external-controller', 'external-controller-tls', 'external-controller-unix', 'external-controller-pipe', 'secret', 'external-ui', 'external-ui-url', 'external-doh-server']) delete config[key];
  }
  return config;
}

