#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');

function personalList(text, name, types) {
  const lines = text.split(/\r?\n/).map(s => s.trim()).filter(s => s && !s.startsWith('#'));
  const seen = new Set();
  return lines.map(line => {
    const parts = line.split(',');
    if (parts.length !== 2 || !types.includes(parts[0]) || /[\x00-\x20,]/.test(parts[1])) throw new Error(name + ': invalid typed rule ' + line);
    if (parts[0] !== 'PROCESS-NAME' && !/^[a-z0-9.-]+$/i.test(parts[1])) throw new Error(name + ': invalid domain');
    if (seen.has(line)) throw new Error(name + ': duplicate rule ' + line);
    seen.add(line);
    return line;
  });
}

function generate(projectRoot = root) {
  const read = file => fs.readFileSync(path.join(projectRoot, file), 'utf8');
  const lock = JSON.parse(read('config/upstream.json'));
  const original = read('vendor/echsfxy/mihomo.js');
  if (crypto.createHash('sha256').update(original).digest('hex') !== lock.files['mihomo.js'].sha256) throw new Error('Upstream snapshot hash differs from config/upstream.json');
  if ((original.match(/function main\(config\)/g) || []).length !== 1) throw new Error('Upstream entry changed; review integration before publishing');
  const settings = JSON.parse(read('Rules/personal/settings.json'));
  if (settings.dns?.ecsMode && !['resolver-default', 'upstream'].includes(settings.dns.ecsMode)) throw new Error('Invalid DNS ECS mode');
  if (!Array.isArray(settings.ai?.regions) || typeof settings.dlsite?.defaultGroup !== 'string') throw new Error('Invalid personal service settings');
  const data = {};
  for (const [name, types] of Object.entries({ 'microsoft-direct': ['DOMAIN'], 'academic-direct': ['DOMAIN-SUFFIX'], 'extra-direct': ['DOMAIN', 'DOMAIN-SUFFIX'], downloads: ['DOMAIN-SUFFIX'], onedrive: ['PROCESS-NAME'] })) data[name] = personalList(read('Rules/personal/' + name + '.list'), name, types);
  const project = JSON.parse(read('config/project.json'));
  let baseUrl = null;
  if (project.repository) {
    if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(project.repository) || !/^[A-Za-z0-9_./-]+$/.test(project.branch) || project.branch.includes('..')) throw new Error('Invalid publication repository or branch');
    baseUrl = `https://raw.githubusercontent.com/${project.repository}/${project.branch}/Rules/generated`;
  }
  const providers = JSON.parse(read('config/provider-map.json'));
  const upstreamContext = vm.createContext({});
  vm.runInContext(original + '\noutput = main({proxies: []});', upstreamContext, { timeout: 4000 });
  const upstreamProviders = upstreamContext.output['rule-providers'];
  if (JSON.stringify(Object.keys(upstreamProviders).sort()) !== JSON.stringify(Object.keys(providers).filter(id => id !== 'dlsite').sort())) throw new Error('Upstream rule providers changed; update the source manifest before publishing');
  for (const [id, provider] of Object.entries(upstreamProviders)) if (providers[id].originalUrl !== provider.url || providers[id].behavior !== provider.behavior) throw new Error('Upstream rule source changed: ' + id);
  const source = [
    '// Generated by Tools/build-scripts.js. Edit src/ or Rules/personal/ and rebuild.',
    '// Echsfxy upstream: https://github.com/' + lock.repository + '/tree/' + lock.commit,
    original.replace('function main(config)', 'function echsfxyMain(config)'),
    'const personalSettings = ' + JSON.stringify(settings, null, 2) + ';',
    'const personalLists = ' + JSON.stringify(data, null, 2) + ';',
    'const managedProviders = ' + JSON.stringify(providers, null, 2) + ';',
    'const rulesBaseUrl = ' + JSON.stringify(baseUrl) + ';',
    read('src/dns-experience.js'),
    read('src/personal-dns.js'),
    read('src/personal.js'),
  ].join('\n\n').replace(/\r\n/g, '\n') + '\n';
  new vm.Script(source, { filename: 'mihomoScript.js' });
  return source;
}

function build({ projectRoot = root, check = false } = {}) {
  const source = generate(projectRoot), file = path.join(projectRoot, 'Script/mihomoScript.js');
  const previous = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : '';
  if (source !== previous) {
    if (check) throw new Error('Generated script is stale; run npm run build');
    fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, source);
  }
  return source !== previous;
}
if (require.main === module) {
  try {
    const args = process.argv.slice(2);
    if (args.some(arg => arg !== '--check')) throw new Error('Usage: node Tools/build-scripts.js [--check]');
    const changed = build({ check: args.includes('--check') });
    console.log(args.includes('--check') ? 'Generated script matches sources.' : 'Built full script (' + (changed ? 'updated' : 'unchanged') + ').');
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
module.exports = { generate, build, personalList };
