#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');

function personalList(text, name, types) {
  const lines = text.split(/\r?\n/).map(s => s.trim()).filter(s => s && !s.startsWith('#'));
  const seen = new Set();
  return lines.map(line => {
    const parts = line.split(',');
    if (parts.length !== 2 || !types.includes(parts[0]) || /[\x00-\x20,]/.test(parts[1])) throw new Error(name + ': invalid typed rule ' + line);
    if (parts[0] !== 'PROCESS-NAME' && !/^[a-z0-9.-]+$/i.test(parts[1])) throw new Error(name + ': invalid domain');
    if (seen.has(line)) throw new Error(name + ': duplicate rule ' + line);
    seen.add(line);
    return line;
  });
}

function generate(projectRoot = root) {
  const read = file => fs.readFileSync(path.join(projectRoot, file), 'utf8');
  const settings = JSON.parse(read('Rules/personal/settings.json'));
  if (settings.dns?.ecsMode && !['resolver-default', 'upstream'].includes(settings.dns.ecsMode)) throw new Error('Invalid DNS ECS mode');
  if (!Array.isArray(settings.ai?.regions) || typeof settings.dlsite?.defaultGroup !== 'string') throw new Error('Invalid personal service settings');
  const data = {};
  for (const [name, types] of Object.entries({ 'microsoft-direct': ['DOMAIN'], 'academic-direct': ['DOMAIN-SUFFIX'], 'extra-direct': ['DOMAIN', 'DOMAIN-SUFFIX'], downloads: ['DOMAIN-SUFFIX'], onedrive: ['PROCESS-NAME'] })) data[name] = personalList(read('Rules/personal/' + name + '.list'), name, types);
  const project = JSON.parse(read('config/project.json'));
  if (!project || typeof project !== 'object' || Array.isArray(project) || typeof project.repository !== 'string' || !/^[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?\/[A-Za-z0-9_.-]+$/.test(project.repository) || ['.', '..'].includes(project.repository.split('/')[1]) || typeof project.branch !== 'string' || !/^[A-Za-z0-9_./-]+$/.test(project.branch) || project.branch.includes('..') || project.branch.startsWith('/') || project.branch.endsWith('/') || project.branch.includes('//')) throw new Error('Invalid publication repository or branch in config/project.json; configure this repository before building');
  const rulesBaseUrl = `https://raw.githubusercontent.com/${project.repository}/${project.branch}/Rules/generated`;
  const manifest = JSON.parse(read('config/rule-sources.json'));
  if (!manifest.rulesets || typeof manifest.rulesets !== 'object' || Array.isArray(manifest.rulesets) || !Object.keys(manifest.rulesets).length) throw new Error('config/rule-sources.json must define published rulesets');
  const ids = Object.keys(manifest.rulesets);
  if (new Set(ids.map(id => id.toLowerCase())).size !== ids.length) throw new Error('Rule provider IDs must be unique ignoring case');
  const providers = Object.fromEntries(Object.entries(manifest.rulesets).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([id, rule]) => {
    if (!/^[a-z0-9][a-z0-9._!@-]*$/i.test(id) || id.endsWith('.') || /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(id) || !rule || !['domain', 'ipcidr'].includes(rule.behavior)) throw new Error('Invalid published rule provider: ' + id);
    return [id, { type: 'http', interval: 86400, proxy: '代理连接', behavior: rule.behavior, format: 'mrs', path: './rules/personal-' + id + '.mrs', url: rulesBaseUrl + '/' + rule.behavior + '/' + id + '.mrs' }];
  }));
  const source = [
    '// Generated by Tools/build-scripts.js. Edit src/ or Rules/personal/ and rebuild.',
    'const ruleProviderDefinitions = ' + JSON.stringify(providers, null, 2) + ';',
    read('src/base.js'),
    'const personalSettings = ' + JSON.stringify(settings, null, 2) + ';',
    'const personalLists = ' + JSON.stringify(data, null, 2) + ';',
    read('src/node-groups.js'),
    read('src/dns-experience.js'),
    read('src/personal-dns.js'),
    read('src/personal.js'),
  ].join('\n\n').replace(/\r\n/g, '\n') + '\n';
  new vm.Script(source, { filename: 'mihomoScript.js' });
  const context = vm.createContext({});
  vm.runInContext(source + '\noutput = main({proxies: [{name: "JP build check", type: "ss", server: "node.example.net", port: 443, cipher: "aes-128-gcm", password: "fixture"}]});', context, { timeout: 4000 });
  validateProviderReferences(context.output);
  return source;
}

function validateProviderReferences(config) {
  const providers = config['rule-providers'] || {};
  function check(id, location) {
    if (!Object.prototype.hasOwnProperty.call(providers, id)) throw new Error('Missing rule provider definition: ' + id + ' (referenced by ' + location + ')');
  }
  function visit(value, location) {
    if (typeof value === 'string') {
      for (const match of value.matchAll(/RULE-SET,([^,()\s]+)/g)) check(match[1], location);
      for (const match of value.matchAll(/rule-set:([a-z0-9._!@,-]+)/gi)) for (const id of match[1].split(',')) check(id, location);
    } else if (Array.isArray(value)) {
      value.forEach((item, index) => visit(item, location + '[' + index + ']'));
    } else if (value && typeof value === 'object') {
      for (const [key, item] of Object.entries(value)) { visit(key, location); visit(item, location + '.' + key); }
    }
  }
  for (const key of ['rules', 'sub-rules', 'dns', 'sniffer']) visit(config[key], key);
}

function build({ projectRoot = root, check = false } = {}) {
  const source = generate(projectRoot), file = path.join(projectRoot, 'Script/mihomoScript.js');
  const previous = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : '';
  if (source !== previous) {
    if (check) throw new Error('Generated script is stale; run npm run build');
    fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, source);
  }
  return source !== previous;
}
if (require.main === module) {
  try {
    const args = process.argv.slice(2);
    if (args.some(arg => arg !== '--check')) throw new Error('Usage: node Tools/build-scripts.js [--check]');
    const changed = build({ check: args.includes('--check') });
    console.log(args.includes('--check') ? 'Generated script matches sources.' : 'Built full script (' + (changed ? 'updated' : 'unchanged') + ').');
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
module.exports = { generate, build, personalList, validateProviderReferences };
